title: "RAKOTONDRAFARA Maminiaina Jacky"
logo:C: \Users\JACKY\Desktop\git\portfolio\jackys00.png
description: "Portfolio Data Scientist - IA, Data analyst"
show_downloads: true
theme: jekyll-theme-minimal
lang: fr
